---
- name: setup tomcat
  hosts: all
  become: yes
  
  tasks:
  - name: install java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on Debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.62/bin/apache-tomcat-9.0.62.tar.gz
      dest: /opt

  - name: extracting tomcat
    unarchive:
      src: /opt/apache-tomcat-9.0.62.tar.gz 
      dest: /opt
      remote_src: yes

  - name: change permissions
    file: 
      path: /opt/apache-tomcat-9.0.62/bin/startup.sh
      mode: 0777

  - name: start tomcat
    shell: nohup ./startup.sh
    args: 
      chdir: /opt/apache-tomcat-9.0.62/bin
    

  




        
